export const FIELD_GENERATE = 'FIELD_GENERATE';
export const FIELD_SET_OPTIONS = 'FIELD_SET_OPTIONS';
export const FIELD_OPEN_CELLS = 'FIELD_OPEN_CELLS';
export const FIELD_CLICK_ON_BOMB = 'FIELD_CLICK_ON_BOMB';
