export const CELL_STATUS_CLOSED = 'CELL_STATUS_CLOSED';
export const CELL_STATUS_OPENED = 'CELL_STATUS_OPENED';
export const CELL_STATUS_QUESTION = 'CELL_STATUS_QUESTION';
export const CELL_STATUS_MARK = 'CELL_STATUS_MARK';
export const GAME_STATUS_WIN = 'GAME_STATUS_WIN';
export const GAME_STATUS_LOOSE = 'GAME_STATUS_LOOSE';
export const GAME_STATUS_GAME = 'GAME_STATUS_GAME';
